### ISSUE TITLE
Small mistake in forumlist_body

### ISSUE THREAD

**Issue by David-NF** [phpBB-Spain/IDLaunch_Fresh#1]
I just noticed that the topics and posts statics are switched.Your style uses topics with post statics and post with topic statics. 

It's about these lines
```<dd class="topics">{L_POSTS}</dd>```
```<dd class="topics">{L_TOPICS}</dd>```

It should be like:
```<dd class="topics">{L_TOPICS}</dd>```
```<dd class="posts">{L_POSTS}</dd>```

**Comment by phpbb-es** [comment]
xD 
No one had noticed that...

Thanks David.
https://github.com/phpBB-Spain/IDLaunch_Fresh/blob/master/IDLaunch_Fresh/template/forumlist_body.html

**Comment by David-NF** [comment]
I took me a while I've seen it, but didn't noticed. Till I took a closer look, glad you fixed it :)
